---
- name:  Enable secure high quality password policy
  command: authconfig --update --passalgo=sha512

- name: Disable Winbind
  command: authconfig --update --disableforcelegacy  --disablewinbind --disablewinbindauth 

- name: Disable authentication through smartcard
  command: authconfig --update --disablesmartcard 

- name: Configure PAM to block logins for failed authentication on accounts.
  blockinfile:
    dest: /etc/pam.d/system-auth
    state: present
    block: |
      auth        [default=die] pam_faillock.so authfail deny=3 unlock_time=604800 fail_interval=900
      auth        required      pam_faillock.so authsucc deny=3 unlock_time=604800 fail_interval=900
    insertafter: auth        sufficient    pam_unix.so

- name: Configure PAM to prevent users from reusing passwords for 24 times
  lineinfile:
    path: /etc/pam.d/system-auth
    line: password    sufficient    pam_unix.so existing_options remember=24
    insertafter: password    sufficient    pam_unix.so.*
    state: present

- name: Remove marker lines
  lineinfile:
    path: /etc/pam.d/system-auth
    regexp: '^.*ANSIBLE MANAGED BLOCK'
    state: absent

- name: Disable empty passwords
  replace:
    dest: /etc/pam.d/password-auth
    regexp: '(nullok )'
    replace: ''

- name: Reconfigure Grub2 to start Audit at boot
  replace:
    dest: /boot/grub2/grub.cfg
    regexp: '(rhgb quiet LANG=en_US.UTF-8$)$'
    replace: '\1 audit=1'

- name: Create new GRUB2 configuration
  command: grub2-mkconfig -o /boot/grub2/grub.cfg

# setup pwquality

- name: Configure Auditd
  copy:
    src: files/audit.rules
    dest: /etc/audit/rules.d/audit.rules
    mode: 0644
    backup: yes

- name: Configure Auditd
  copy:
    src: files/audit.rules
    dest: /etc/audit/audit.rules
    mode: 0644
    backup: yes

- name: Restart Auditd
  systemd:
    name: auditd
    state: started
    enabled: yes

- name: Ensure the 'Gnome desktop' environment group is not installed
  yum:
    name: "@^GNOME Desktop"
    state: absent
    update_cache: no

- name: Ensure the 'KDE desktop' environment group is not installed
  yum:
    name: "@^KDE Plasma Workspaces"
    state: absent
    update_cache: no

- name: Ensure the 'Mate desktop' environment group is not installed
  yum:
    name: "@^MATE Desktop"
    state: absent
    update_cache: no

- name: Enable SSH login only with sysadm accounts
  shell: setsebool -P ssh_sysadm_login 1

- name: Disable unconfined accounts
  shell: setsebool -P unconfined_login 0

- name: Disable for xguests the possibility to execute
  shell: setsebool -P xguest_exec_content 0

- name: Disable for xguests the possibility to execute
  shell: setsebool -P xguest_exec_content 0
